### ISSUE TITLE
Don't sort context menu item by selector

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/lumino#202]
### Problem

Currently the context menu elements are sorted _by selector_ and by rank. This breaks the separation of concern and create somewhat strange positioning like the `Paste` item in JupyterLab core:

![](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/ui-tests/reference-output/screenshots/contextmenu_file.png)

> In the above example, it would also make more sense to put the `New...` items first (but this is blocked by the selector sort).

### Proposed Solution

It would make sense to sort only by rank (following the separation of concern rule). 

> This probably needs to be implemented as optional constructor argument to avoid breaking the API.

### Additional context

Code at play:

https://github.com/jupyterlab/lumino/blob/cb80c56bfba800e9a8e7c2ec16e8e96f5df36be5/packages/widgets/src/contextmenu.ts#L316-L322

**Comment by telamonian** [comment]
+100 to this suggestion. The only time I met Chris Colbert in person we talked about this exact thing. At the time it was making it impossible to group the "cut", "copy", and "paste" items together in the filebrowser menu.

The problem is that `rank` is static. On the other hand, a contextmenu item is by design meant to be able to be used in the contextmenu for several different regions in the app. So if an item is supposed to appear as the third out of ten items in one region, but as the last out of five in another, you won't be able to do that with just rank. Not that selector precedence is really going to make your life that much easier here either, but it's at least possible to do some amount of dynamic reordering based on region with it.

The obvious problem child here is again "paste", which needs to be in one place when you contextmenu click on a file in the filebrowser, and in another place when you contextmenu click on an empty region of the filebrowser.

I'm not saying that there isn't a better solution, I'm just not sure what it is. Ideally we would be able to order the items in a given region's contextmenu in any fixed order, according to a dev's intent.

**Comment by fcollonval** [comment]
Thanks for kicking in @telamonian 

The point of different ordering depending on the app region makes sense. I don't have neither a good solution to address that point (maybe splitting the context menu from app-wise to region-wise). My feeling though is that when item visibility definitely depends on the region, order is not. It sounds strange to me to have a menu that say, if you click on A the menu is 1 | 2 | 3, and on B the menu is 3 | 1. It seems like a bad practice - a bit like inconsistent positioning of Cancel and Ok buttons in dialog.

Apparently Google Guideline used to be:

> Menus with static content should have the most frequently used menu items placed at the top of the menu.
> Menus with dynamic content may have other behavior, such as placing previously used fonts at the top of the menu. The order can change based on user actions.

Xref: https://ux.stackexchange.com/questions/79123/order-of-items-in-a-context-menu - did not find those quotes in the current Google guideline.

Anyway, I'll push this easy proposal that should fulfill the need for JLab.
