### ISSUE TITLE
Update RTD to include multiple versions of Lumino

### ISSUE THREAD

**Issue by afshin** [jupyterlab/lumino#336]
The [Lumino `readthedocs.io` site](https://lumino.readthedocs.io/en/latest/) should support both Lumino 1 and Lumino 2 docs and needs a re-visit for maintenance.

**Comment by gabalafou** [comment]
I need to familiarize myself more with Read the Docs, so I'm willing to try to figure out how to 

- upgrade current Read the Docs
- add version support

But I don't think I have enough of the big picture of Lumino to make content/copy changes and contributions here.

**Comment by afshin** [comment]
>  make content/copy changes and contributions here

Don't worry, the content for now is all contained within doc strings, so if you can generate an RTD page that shows the API documentation for the current version and the previous version, we are good.

**Comment by blink1073** [comment]
It should be controllable by having an active "Version" for the 1.x branch.  See JupyterLab for example:

![image](https://user-images.githubusercontent.com/2096628/183974708-f263e4f0-f180-4d29-872e-7e1359c0af9a.png)

**Comment by blink1073** [comment]
@gabalafou, what is your ReadTheDocs username?

**Comment by gabalafou** [comment]
I didn't have a Read the Docs username before, but it is now the same as my GitHub username: gabalafou.

**Comment by blink1073** [comment]
Great, you should have an invite now!

**Comment by gabalafou** [comment]
With #354 merged, I went ahead and made the following changes in the Read The Docs settings:

- Deactivated version `stable`
- Activated version `1.x`
- Set `latest` to point to `main` instead of `master`. 
  - Previously it was blank. The RTD UI says, "Leave empty to use the default value for your VCS (eg. trunk or master)." However, the [versions page](https://readthedocs.org/projects/lumino/versions/) was still showing `latest` pointing to `master` until I set it explicitly to `main` under Admin > Advanced Settings > Default branch.

I discussed the desired final config with @afshin on Tuesday, and the above changes reflect that conversation. He said that he envisioned just two RTD versions: 1.x and latest.

You should now be able to see all of these changes (RTD settings plus code changes from #354) at https://lumino.readthedocs.io.

Therefore, I'm going to close this issue for now.

**Comment by gabalafou** [comment]
Oh, I almost forgot: a few things before we completely move on from this issue.

- @fcollonval [suggested](https://github.com/jupyterlab/lumino/pull/354#pullrequestreview-1077305104) that we do a follow-up to have Lumino [use the Pydata Sphinx Theme, so I created a GitHub issue #356](https://github.com/jupyterlab/lumino/issues/356) for that. I didn't assign myself because I'm not sure yet whether I will have time for it

- There are a lot of Typedoc warnings that get emitted now when you run `yarn docs` from the root of the repo, so I also created a GitHub issue [Fix Typedoc warnings #357](https://github.com/jupyterlab/lumino/issues/357).

- Should we remove the old GitHub Pages build of the docs? https://jupyterlab.github.io/lumino/

**Comment by fcollonval** [comment]
> * Deactivated version `stable`

I would prefer to keep it. It is a good practice to provide a default endpoint that people can bookmark.

**Comment by gabalafou** [comment]
@afshin can you respond to @fcollonval's comment above? 

I was just following your guidance when setting up RTD to just have `latest` and `1.x` but not `stable`.

Reminder that `stable` points (I think) to whichever year-month-day-format tag is the latest in Lumino repo, which at the time of this writing is [v2022.8.22-alpha.1](https://github.com/jupyterlab/lumino/releases/tag/v2022.8.22-alpha.1), I think (although I'm curious whether RTD will pick up a tag with an `-alpha` suffix as `stable`).

**Comment by fcollonval** [comment]
> [from documentation](https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working) _We only consider non pre-releases for the stable version of your documentation._
